### ISSUE TITLE
README Issue : 3rd point webpack-dev-server

### ISSUE THREAD

**Issue by LyzioOh** [retroalgic/react-on-rails-hot-minimal#2]
Maybe i miss understood but when i look at the README and the code i guess there is an lack of concistency .

In the Readme.md
`add "react-hot-loader/patch", "webpack-dev-server/client?http://localhost:3500" to webpack entry before your source file (in the same chunk that contains your source file if you have multiple chunks)`

in client/webpack.config.js

```
const config = {
  entry: [
    "babel-polyfill",
    "react-hot-loader/patch",
    "entry"
  ],
```

May i submit a PR to make the doc coherent, or does i have misunderstood something ?

**Comment by mongjong59** [comment]
Thanks, @EEtancelin. You're right. I forgot to update the README. "webpack-dev-server/client?http://localhost:3500" is unnecessary and I will just remove it.
